In [1]:
import os
import sys
import logging
from pathlib import Path
from dotenv import load_dotenv
import torch
from torch import nn
import pandas as pd
from huggingface_hub import login

logging.basicConfig(
    level=logging.INFO,
    format="%(name)s | %(levelname)s | %(message)s",
)

torch.manual_seed(123)

# src_path = Path.cwd().parent / "src"
# if src_path.exists() and str(src_path) not in sys.path:
#     sys.path.insert(0, str(src_path))

# print(f"Added to sys.path: {src_path}")
load_dotenv()  # reads .env file from the current directory

PATH_DATA = Path.cwd().parent.parent / ".data"
PATH_GPT2_124M_WEIGHTS = PATH_DATA / "model_weights" / "gpt2" / "124M" / "parameters.pickle.gz"

In [2]:
login(os.getenv("HF_TOKEN"))

httpx | INFO | HTTP Request: GET https://huggingface.co/api/whoami-v2 "HTTP/1.1 200 OK"
Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.
huggingface_hub._login | WARNING | Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

In [4]:
from tgedr_lm.classifier.gpt2.etl import Gpt2ClassifierEtl

etl = Gpt2ClassifierEtl({
  "dataset": "jtviegas/financial_phrasebank"
})

In [5]:
etl.run()

tgedr_dataops_abs.etl | INFO | [run|in]
httpx | INFO | HTTP Request: HEAD https://huggingface.co/datasets/jtviegas/financial_phrasebank/resolve/main/README.md "HTTP/1.1 404 Not Found"
httpx | INFO | HTTP Request: GET https://huggingface.co/api/datasets/jtviegas/financial_phrasebank "HTTP/1.1 200 OK"
httpx | INFO | HTTP Request: HEAD https://huggingface.co/datasets/jtviegas/financial_phrasebank/resolve/3e83f8bf254692c4f873567632c2e43e515a4408/financial_phrasebank.py "HTTP/1.1 404 Not Found"
httpx | INFO | HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/jtviegas/financial_phrasebank/jtviegas/financial_phrasebank.py "HTTP/1.1 404 Not Found"
httpx | INFO | HTTP Request: HEAD https://huggingface.co/datasets/jtviegas/financial_phrasebank/resolve/3e83f8bf254692c4f873567632c2e43e515a4408/README.md "HTTP/1.1 404 Not Found"
httpx | INFO | HTTP Request: GET https://huggingface.co/api/datasets/jtviegas/financial_phrasebank/revision/3e83f8bf254692c4f873567632c2e43e515a4408 "HTTP/1.1 200 OK"
httpx | INFO | HTTP Request: HEAD https://huggingface.co/datasets/jtviegas/financial_phrasebank/resolve/3e83f8bf254692c4f873567632c2e43e515a4408/.huggingface.yaml "HTTP/1.1 404 Not Found"
httpx | INFO | HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=jtviegas/financial_phrasebank "HTTP/1.1 503 Service Temporarily Unavailable"
httpx | INFO | HTTP Request: GET https://huggingface.co/api/datasets/jtviegas/financial_phrasebank/tree/3e83f8bf254692c4f873567632c2e43e515a4408/data?recursive=true&expand=false "HTTP/1.1 200 OK"
httpx | INFO | HTTP Request: GET https://huggingface.co/api/datasets/jtviegas/financial_phrasebank/tree/3e83f8bf254692c4f873567632c2e43e515a4408?recursive=false&expand=false "HTTP/1.1 200 OK"
tgedr_lm.classifier.gpt2.hyperparam_search | INFO | [search|in] (GPT2Classifier(
  (tok_emb): Embedding(50257, 768)
  (pos_emb): Embedding(1024, 768)
  (drop_emb): Dropout(p=0.1, inplace=False)
  (trf_blocks): Sequential(
    (0): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (1): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (2): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (3): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (4): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (5): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (6): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (7): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (8): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (9): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (10): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
    (11): TransformerBlock(
      (att): MultiHeadAttention(
        (W_query): Linear(in_features=768, out_features=768, bias=False)
        (W_key): Linear(in_features=768, out_features=768, bias=False)
        (W_value): Linear(in_features=768, out_features=768, bias=False)
        (out_projection): Linear(in_features=768, out_features=768, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (ff): FeedForward(
        (layers): Sequential(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU()
          (2): Linear(in_features=3072, out_features=768, bias=True)
        )
      )
      (norm1): LayerNormalization()
      (norm2): LayerNormalization()
      (drop_shortcut): Dropout(p=0.1, inplace=False)
    )
  )
  (final_norm): LayerNormalization()
  (out_head): Linear(in_features=768, out_features=3, bias=False)
), Dataset({
    features: ['input_ids', 'labels'],
    num_rows: 1162
}), Dataset({
    features: ['input_ids', 'labels'],
    num_rows: 291
}), 3)
tgedr_lm.classifier.gpt2.hyperparam_search | INFO | Running automatic hyperparameter search (Optuna backend)...
[I 2026-07-13 23:01:04,659] A new study created in memory with name: no-name-69aaa74d-0637-4d4c-b988-a663c9751a53
/home/jtv/code/jtviegas/languagemodels/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 23:20:59,228] Trial 0 finished with value: 0.697594501718213 and parameters: {'learning_rate': 1.0033163353734045e-05, 'weight_decay': 0.030854942318717785, 'num_train_epochs': 6, 'per_device_train_batch_size': 8, 'warmup_steps': 0.15662725142576536}. Best is trial 0 with value: 0.697594501718213.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 23:30:48,785] Trial 1 finished with value: 0.7216494845360825 and parameters: {'learning_rate': 2.9235348334815372e-05, 'weight_decay': 0.08752171662623555, 'num_train_epochs': 3, 'per_device_train_batch_size': 8, 'warmup_steps': 0.1590847898741382}. Best is trial 1 with value: 0.7216494845360825.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-07-13 23:39:55,774] Trial 2 finished with value: 0.7216494845360825 and parameters: {'learning_rate': 0.00021262452270401485, 'weight_decay': 0.09884776062941672, 'num_train_epochs': 3, 'per_device_train_batch_size': 16, 'warmup_steps': 0.1789902973244572}. Best is trial 1 with value: 0.7216494845360825.
tgedr_lm.classifier.gpt2.hyperparam_search | INFO | [search|out] => {'learning_rate': 2.9235348334815372e-05, 'weight_decay': 0.08752171662623555, 'num_train_epochs': 3, 'per_device_train_batch_size': 8, 'warmup_steps': 0.1590847898741382}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

tgedr_lm.classifier.gpt2.etl | INFO | Final evaluation metrics: {'eval_loss': 0.7572835683822632, 'eval_accuracy': 0.6948453608247422, 'eval_precision': 0.6155325288928074, 'eval_recall': 0.5386890870503183, 'eval_f': 0.5584282473553487}
httpx | INFO | HTTP Request: POST https://huggingface.co/api/repos/create "HTTP/1.1 409 Conflict"

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

httpx | INFO | HTTP Request: POST https://huggingface.co/api/validate-yaml "HTTP/1.1 200 OK"
httpx | INFO | HTTP Request: POST https://huggingface.co/api/validate-yaml "HTTP/1.1 200 OK"
httpx | INFO | HTTP Request: POST https://huggingface.co/api/models/jtviegas/gpt2classifier/preupload/main "HTTP/1.1 200 OK"
httpx | INFO | HTTP Request: POST https://huggingface.co/jtviegas/gpt2classifier.git/info/lfs/objects/batch "HTTP/1.1 200 OK"
httpx | INFO | HTTP Request: GET https://huggingface.co/api/models/jtviegas/gpt2classifier/xet-write-token/main "HTTP/1.1 200 OK"

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

httpx | INFO | HTTP Request: POST https://huggingface.co/api/models/jtviegas/gpt2classifier/commit/main "HTTP/1.1 200 OK"
tgedr_dataops_abs.etl | INFO | [run|out] => None